language: python
python:
- '3.5'
services: postgresql
install:
- pip install -r web/requirements.txt
- pip install coverage==4.3
- psql -c "CREATE DATABASE personal_site;" -U postgres
before_script:
- cd web
#
# Code climate configuration
#
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
#
# Application
#
- mv ./renefernandez_com/config.sample.py ./renefernandez_com/config.py
- python manage.py makemigrations
- python manage.py migrate
script:
- coverage run --source='.' manage.py test
after_success:
- coverage report
- coverage xml
- ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
- cd ..
- tar -czf package.tgz web
- export SSHPASS=$DEPLOY_PASS
- sshpass -V
- sshpass -e scp -o StrictHostKeyChecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
addons:
  apt:
    packages:
    - sshpass
  ssh_known_hosts: "$DEPLOY_HOST"
