language: python
python:
  - "2.7"

services: postgresql

install:
  - pip install -r ./renefernandezcom/pip-requirements.txt
  - psql -c "CREATE DATABASE personal_site;" -U postgres

before_script:
  - mv ./renefernandezcom/renefernandezcom/ci_settings.py.sample ./renefernandezcom/renefernandezcom/settings.py
  - cd renefernandezcom
  - python manage.py migrate

script:
  - python manage.py test
