language: python
python:
  - "2.7.10"

services: postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage==4.3
  - psql -c "CREATE DATABASE personal_site;" -U postgres

before_script:
  - cp requirements.txt ./web
  - cd web
  - mv ./renefernandez_com/config.sample.py ./codeproject/config.py
  - python manage.py makemigrations
  - python manage.py migrate
script:
- coverage run --source='.' manage.py test

script:
  - python manage.py test


