language: python
python:
- '3.5'
services: postgresql
install:
- pip install -r requirements.txt
- pip install coverage==4.3
- psql -c "CREATE DATABASE personal_site;" -U postgres
before_script:
- cp requirements.txt ./web
- cd web
#
# Code climate configuration
#
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
#
# Application
#
- mv ./renefernandez_com/config.sample.py ./renefernandez_com/config.py
- python manage.py makemigrations
- python manage.py migrate
script:
- coverage run --source='.' manage.py test
after_success:
- coverage report
- coverage xml
- ls -la
- ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
- cd ..
- tar -czf package.tgz web
- export SSHPASS=$DEPLOY_PASS
- sshpass -V
- sshpass -e scp -o StrictHostKeyChecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
env:
  global:
  - secure: AWi9NxkiVl7UYWUdaCvRO2+gornwvDFLu/17UJMeAorcgYIOvwzaNqN0nL8yUA62YP3M3rYfTykYLODxu/bjOSUpumywz8JYhvtD7HwQOwG+9ApePh7csBIeogjprIZGq4z8eKp70cOueH3cEsKsbLZ0YglENp5Vh1H/HSmSjL1rmWZKIL86UMedNmIGjpKcESEOSKc1+RwWapvTDkVVgd4P/OZSiGdMmmp8AjDf4j33ErCV1vGCaxQwqoX9tmsbK4ttXVr5FnQcApqGCh+wVMaMgiVwggoCDPuR2zRYW9M8ZnIWAczw/VVYPHoqsHVU9HBXetTglHBGYAehgdVk47gPIndL25zma/b96WBrs9lxuUCKdJ/iQrsbeEwI5KQC7IqF9EOf1oJCr36/P1tNXFVjvLrzkU6dpIYhJVWYGOdIWj4+XKdldOlhsUHDZWGLAs1gsJItdPkVOcHCZMklXrRWCQH3z7Gst3zeUNL72kS2x6joAO0l8gQvhYHTtn6bsXX+pgLX9eMbaBpJG5HFUcxPUq4Xdaa9bL4k8haYx545ZZfh5AhS9G5sWAOOykltCmKPIPRovBE879PRd+eRJZQhmRXSvAPdyfQA0RuopiR5gEpU843NCKlp8yukzx2KpEu8YHkGw/6xydYOqy9WE+o8HDIdxnOp+6iM1anEkZU=
  - secure: kC0BNTLn/eCImUnoZbqluRQ7IT98OUfhpcRrEn6MqLJZOE1jVp0yTlUXoEKkZGJ/Sf2eQS9LSux0TCyI+kncE9svvNn2Z/hVh4MJ1Y479rR4NHx/0zYg/xr6E+sNQRBOnifXmsb/ftKecYY0CziRwINPiisJCTUenYlVAGO9ci23PnwwpfLpjnl48lbiLDK2JJLFNi6ZXeDLsAUqYdCF0ulV+qCDOi9d+ICkzCNhwZvhL2B71YAVfFFXUiNQ2bJf3GlFxBDt0m4wOPhr+SBaOBzjMp0EnHFXAqab8OtUeUfcY7GQ8LrUlDmIwP/iNoh0Rl04bxlSpeEBldfCqNhIN/6/A+PVjQwHcFfSCfZ3zJ1SAu6oshbly4PtHRLS3p9hgPUuipquplsfzuJpEP1W8Vrox9V3mv09aeEk3s1iR6zPM7on1tBj97YV1MW804iow1u4UJ0fIDmW3YbPt8r6YcpweINTUZGaN2E8EHqfxYCfVPdu6OdFxwDIuxzknRaWYYkhL9JpImru75Wy9+4lJ0JfM4zjpjvJRQDosIRWON54wpFk6LMU0r8Vx0kDDXSP/VhtvTjVn46jGeFRsJqWGRJh/Tf570mel8T1eP6EsFUIeIai0reEqxzUXnXWKjiig8cl63clFe9fIuUpPdK4DxQedsnhyL/Ft8lTPGJvWqw=
  - secure: dzRIs/xRLFSlC16lC3/qbhz9srrg96eKmpQA3bRadjONpsSK/6ayJvup8il2vim4o6pLDrhMg736M0t73Jv++0zX1Bz1DZLCpAy7CelK64RVg2NS/r7R96/kA1xoAPbtL5Zw6Y7jdpuKNf359DT2/03iwlTG3fEoLLyQ/GbjEUai5+I/YbRdtUdrqxTivRYJjBTCULAWEyJIZE+ZQjnNNEqko+hJFi5De9gE4FZMcbEuG26UeZN+wThABImdEcbcJZn9WZjBQvNFICgKwYu1VQX1E18+c3WjAcUtOo8AQDupVpVRdFCnMT1SyTYl/JG28U9sTRTuEJUGw+MJabM3SBP1bzpYdrkyzlI2MpefdAm7dWawO2E9srtRkCc1zQAzKAG8uvDLOYdvEOwYixVG/W1jNp/Pt4aj4VY+bgMwSSLU//IyZ86SkAfFFrooRb6/E/UCTDFIpg1oxEFIj4GnmjzrO1BLXRL3Mu5z7yE9ot5GBQ34nsQS0EGj2HpxcLI9I8ztgwOB8Z14w1yNyRUMmYZxDQRNI40oHFixnE6naDheA5stsOP+liEZhUC0iysa1P+z9bW7+BNSoCIh02rqvkDzjOtV78N9yw8cP5bruHwycg6FM6ITrcf3mjUtpqQstgnkilOZphUwLHmRQwe1kiCHlCGDuRD95MMY9mnfAF8=
  - secure: ILmhBG0fsAafHV93x9ctUvXJk6qI1MiuctwZxLWg9UOs4SME/XuzeQaqHeRqHsg7Zn9hHAxXN0HGmY95zhlWks0NJZlN/QFb5JIUOWlJ8y09VDjUTb0G7FVcv8B4/uQMwjAYKifPVy7KNsH8YOTaOfflo60/NY2AgBpDMXLp/X/n6TKEyN/+1YYbC3t7uFzbtZ/CkIkyUrB1Rw9JyKtUfIhCHaF3IZWADmZkoZwrRKi1BPyENPgTRxsEXdgyHso35FeWnRfjqRCuvLGbmlyKC7MJdOMSb4RUmCG2BlgUeSmHRFyfmx8wjqwOULcTi0Rsor8ieAlzgakEMDdS3SnDkfgvjAOpNoNBOL8jP53lU1GiaspYnIXXl7ClnTnJklwRC8Gg3gUuGFOb1wiy4ujh58aYUXGGfliqVdiPNcG/uhq7GM9SPJ9fdx+bymM7zNkoTgdVQeMMLV+/7R96FxsEpjvB0lIxDOReU++Cqo229IOOqSlGSGh+kDYimr859uW0+V1F6IZOl8wspZX+MQBXlUYnXeLKNjvib+tSMf4uShmHn3Pe+MUxiWCQVa4cSt3sYFfQ3VITnCeIu08K1zbdqe+x7F1zPVQBn3TjPXPl92udijdXR9zGbCKTyL5TKSsQOMdwpIPJzYWj8u3beLDTVp+nA8JAoHw7x6J05NGsQ9Y=
addons:
  apt:
    packages:
    - sshpass
  ssh_known_hosts: "$DEPLOY_HOST"
